name: Integration (Install + Uninstall + Test)

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libglfw3-dev dkms linux-headers-$(uname -r)

      - name: Run install script
        env:
          SUDO_USER: runner
        run: |
          chmod +x ./install.sh
          ./install.sh

      - name: Check if necessary files were created
        run: |
          test -f /sys/module/yeetmouse/parameters/AccelerationMode
          test -f /etc/yeetmouse.conf
          test -f /usr/lib/systemd/system/yeetmouse.service
          yeetmousectl dump | grep -q "accelMode"

      - name: Run uninstall script
        env:
          SUDO_USER: runner
        run: |
          sudo ./uninstall.sh --purge-config